# Generated by Django 5.2.5 on 2025-11-27 12:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dish', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='comment',
            field=models.TextField(default='コメントはありません', verbose_name='コメント'),
        ),
        migrations.AddField(
            model_name='dish',
            name='image',
            field=models.ImageField(blank=True, upload_to='dishs', verbose_name='イメージ'),
        ),
        migrations.AddField(
            model_name='dish',
            name='posted_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='投稿日時'),
            preserve_default=False,
        ),
    ]
